sudo: required
language: cpp
dist: trusty

git:
  depth: 10

os:
  - linux

compiler:
  - g++
  - clang++

arch:
  packages:
    - cmake
    - gcc
    - clang
    - boost
    - botan

  script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - make -j4

script:
  - "curl -s https://raw.githubusercontent.com/Jackarain/arch-travis/master/arch-travis.sh | bash"

branches:
  only:
    - master

